#!/bin/bash -e

reporoot=$(git rev-parse --show-toplevel)

if [[ -f $reporoot/tox.ini ]]; then
    toxenvs=( "lint" "static" "unit" )
    for toxenv in "${toxenvs[@]}"; do
        if ! [[ -z $(tox -a | grep $toxenv) ]]; then
            tox -e $toxenv
        fi
    done
fi

